---
title: "Chapter 5 Notes and Exercises"
author: "Matthias Grenié"
date: "9 août 2016"
output: pdf_document
---

# Chapter 5

## Notes

Implementing the first specified model in 5.1:
\begin{align*}
  D_i \sim& \text{Normal}(\mu_i, \sigma) \\
  \mu_i =& \alpha + \beta_A A_i \\
  \alpha \sim& \text{Normal}(10, 10) \\
  \beta_A \sim& \text{Normal}(0, 10) \\
  \sigma \sim& \text{Uniform}(0, 10)
\end{align*}

```{r}
library(rethinking)

# Data exploration
data("WaffleDivorce")
head(WaffleDivorce)

# Standardize Median Marriage Age
d = WaffleDivorce
d$MedianAgeMarriage.s = scale(d$MedianAgeMarriage, T, T)

# Model
m5.1 = map(
  alist(
    Divorce ~ dnorm(mu, sigma),
    mu <- alpha + beta * MedianAgeMarriage.s,
    alpha ~ dnorm(10, 10),
    beta ~ dnorm(0, 10),
    sigma ~ dunif(0, 10)
  ),
  data = d
)

# Plot
MAM.seq = seq(-3, 3.5, length.out = 30)
mu = link(m5.1, data = data.frame(MedianAgeMarriage.s = MAM.seq))
mu.PI = apply(mu, 2, PI, prob = 0.89)

plot(Divorce ~ MedianAgeMarriage.s, data = d, col = rangi2)
abline(m5.1)
shade(mu.PI, MAM.seq)
```

Now with additional predictor (median marriage age and mediam marriage rate):

```{r}
d$Marriage.s = scale(d$Marriage)

m5.3 = map(
  alist(
    Divorce ~ dnorm(mu, sigma),
    mu <- alpha + beta_a * MedianAgeMarriage.s + beta_r * Marriage.s,
    alpha ~ dnorm(10, 10),
    beta_a ~ dnorm(0, 10),
    beta_r ~ dnorm(0, 10),
    sigma ~ dunif(0, 10)
  ),
  data = d
)

plot(precis(m5.3))
```


### Residual plots

### Counterfactual plot

```{r}
a.avg = mean(d$MedianAgeMarriage.s)
r.seq = seq(-3, 3, length.out = 30)

pred.data = data.frame(
  Marriage.s = r.seq,
  MedianAgeMarriage.s = a.avg
)

mu = link(m5.3, data = pred.data)
mu.mean = apply(mu, 2, mean)
mu.PI = apply(mu, 2, PI)

r.sim = sim(m5.3, data = pred.data, n = 1e4)

r.PI = apply(r.sim, 2, PI)

plot(Divorce ~ Marriage.s, data = d)
lines(r.seq, mu.mean)
shade(mu.PI, r.seq)
shade(r.PI, r.seq)
```


## Practice
